/**
 * Maps common school abbreviations and nicknames to their full database names.
 * Extracted from the Reddit ingestion pipeline for shared use across the app.
 *
 * Used by:
 * - School autocomplete API (to match abbreviation searches like "MIT", "UCLA")
 * - Reddit data ingestion script (to map Reddit posts to our schools table)
 *
 * Keys are lowercase. Values must match the `name` column in the `schools` table exactly.
 */
export const SCHOOL_ABBREVIATIONS: Record<string, string> = {
  "mit": "Massachusetts Institute of Technology",
  "caltech": "California Institute of Technology",
  "upenn": "University of Pennsylvania",
  "penn": "University of Pennsylvania",
  "uchicago": "University of Chicago",
  "washu": "Washington University in St Louis",
  "gatech": "Georgia Institute of Technology-Main Campus",
  "georgia tech": "Georgia Institute of Technology-Main Campus",
  "gt": "Georgia Institute of Technology-Main Campus",
  "uva": "University of Virginia-Main Campus",
  "umich": "University of Michigan-Ann Arbor",
  "umich lsa": "University of Michigan-Ann Arbor",
  "unc": "University of North Carolina at Chapel Hill",
  "ucb": "University of California-Berkeley",
  "uc berkeley": "University of California-Berkeley",
  "berkeley": "University of California-Berkeley",
  "cal": "University of California-Berkeley",
  "ucla": "University of California-Los Angeles",
  "ucd": "University of California-Davis",
  "uc davis": "University of California-Davis",
  "ucsb": "University of California-Santa Barbara",
  "uc santa barbara": "University of California-Santa Barbara",
  "ucsd": "University of California-San Diego",
  "uc san diego": "University of California-San Diego",
  "uci": "University of California-Irvine",
  "uc irvine": "University of California-Irvine",
  "ucsc": "University of California-Santa Cruz",
  "uc santa cruz": "University of California-Santa Cruz",
  "ucr": "University of California-Riverside",
  "uc riverside": "University of California-Riverside",
  "nyu": "New York University",
  "bu": "Boston University",
  "bc": "Boston College",
  "cmu": "Carnegie Mellon University",
  "usc": "University of Southern California",
  "northeastern": "Northeastern University",
  "northwestern": "Northwestern University",
  "jhu": "Johns Hopkins University",
  "cornell": "Cornell University",
  "columbia": "Columbia University in the City of New York",
  "brown": "Brown University",
  "dartmouth": "Dartmouth College",
  "emory": "Emory University",
  "williams": "Williams College",
  "amherst": "Amherst College",
  "cal poly slo": "California Polytechnic State University-San Luis Obispo",
  "cal poly": "California Polytechnic State University-San Luis Obispo",
  "rice": "Rice University",
  "duke": "Duke University",
  "vanderbilt": "Vanderbilt University",
  "georgetown": "Georgetown University",
  "tufts": "Tufts University",
  "notre dame": "University of Notre Dame",
  "purdue": "Purdue University-Main Campus",
  "uiuc": "University of Illinois Urbana-Champaign",
  "ut austin": "The University of Texas at Austin",
  "uw madison": "University of Wisconsin-Madison",
  "virginia tech": "Virginia Polytechnic Institute and State University",
  "william and mary": "William & Mary",
  "wellesley": "Wellesley College",
  "swarthmore": "Swarthmore College",
  "pomona": "Pomona College",
  "barnard": "Barnard College",
  "bowdoin": "Bowdoin College",
  "colby": "Colby College",
  "middlebury": "Middlebury College",
  "harvey mudd": "Harvey Mudd College",
  "ufl": "University of Florida",
  "uf": "University of Florida",
  "penn state": "Pennsylvania State University-Main Campus",
  "ohio state": "Ohio State University-Main Campus",
  "osu": "Ohio State University-Main Campus",
  "uw": "University of Washington-Seattle Campus",
  "u of washington": "University of Washington-Seattle Campus",
  "umd": "University of Maryland-College Park",
  "rutgers": "Rutgers University-New Brunswick",
  "umass amherst": "University of Massachusetts-Amherst",
  "umass": "University of Massachusetts-Amherst",
  "case western": "Case Western Reserve University",
  "cwru": "Case Western Reserve University",
  "wpi": "Worcester Polytechnic Institute",
  "rpi": "Rensselaer Polytechnic Institute",
  "lehigh": "Lehigh University",
  "villanova": "Villanova University",
  "pitt": "University of Pittsburgh-Pittsburgh Campus",
  "asu": "Arizona State University-Tempe",
  "csu long beach": "California State University-Long Beach",
  "stanford": "Stanford University",
  "harvard": "Harvard University",
  "yale": "Yale University",
  "princeton": "Princeton University",
  "michigan": "University of Michigan-Ann Arbor",
  "wisconsin": "University of Wisconsin-Madison",
  "minnesota": "University of Minnesota-Twin Cities",
  "florida": "University of Florida",
  "georgia": "University of Georgia",
  "uga": "University of Georgia",
  "ut": "The University of Texas at Austin",
  "texas a&m": "Texas A & M University-College Station",
  "tamu": "Texas A & M University-College Station",
  "ucm": "University of California-Merced",
  "uc merced": "University of California-Merced",
  "sdsu": "San Diego State University",
  "sfsu": "San Francisco State University",
  "csulb": "California State University-Long Beach",
  "rit": "Rochester Institute of Technology",
  "stevens": "Stevens Institute of Technology",
  "drexel": "Drexel University",
  "fordham": "Fordham University",
  "tulane": "Tulane University of Louisiana",
  "wake forest": "Wake Forest University",
  "william & mary": "William & Mary",
  "w&m": "William & Mary",
  "wm": "William & Mary",
  "colgate": "Colgate University",
  "hamilton": "Hamilton College",
  "wesleyan": "Wesleyan University",
  "oberlin": "Oberlin College",
  "macalester": "Macalester College",
  "carleton": "Carleton College",
  "reed": "Reed College",
  "colorado college": "Colorado College",
  "kenyon": "Kenyon College",
  "bates": "Bates College",
  "claremont mckenna": "Claremont McKenna College",
  "cmc": "Claremont McKenna College",
  "scripps": "Scripps College",
  "pitzer": "Pitzer College",
  "smith": "Smith College",
  "bryn mawr": "Bryn Mawr College",
  "mount holyoke": "Mount Holyoke College",
  "colorado school of mines": "Colorado School of Mines",
  "mines": "Colorado School of Mines",
  "cooper union": "The Cooper Union for the Advancement of Science and Art",
  "babson": "Babson College",
  "bentley": "Bentley University",
  "stony brook": "Stony Brook University",
  "binghamton": "Binghamton University",
  "bing": "Binghamton University",
  "buffalo": "University at Buffalo",
  "uconn": "University of Connecticut",
  "iowa": "University of Iowa",
  "iowa state": "Iowa State University",
  "michigan state": "Michigan State University",
  "msu": "Michigan State University",
  "indiana": "Indiana University-Bloomington",
  "iu": "Indiana University-Bloomington",
  "calpoly": "California Polytechnic State University-San Luis Obispo",
  "calpoly pomona": "California State Polytechnic University-Pomona",
  "calpoly slo": "California Polytechnic State University-San Luis Obispo",
  "washington and lee": "Washington and Lee University",
  "rowan": "Rowan University",
  "njit": "New Jersey Institute of Technology",
  "wash u": "Washington University in St Louis",
  "wustl": "Washington University in St Louis",
  "umich ross": "University of Michigan-Ann Arbor",
  "uic": "University of Illinois Chicago",
  "uflorida": "University of Florida",
  "gtech": "Georgia Institute of Technology-Main Campus",
  "bama": "The University of Alabama",
  "baylor": "Baylor University",
  "tcnj": "The College of New Jersey",
  "georgetown sfs": "Georgetown University",
  "georgetown mse": "Georgetown University",
  "umn": "University of Minnesota-Twin Cities",
  "umn twin cities": "University of Minnesota-Twin Cities",
  "nc state": "North Carolina State University at Raleigh",
  "ncsu": "North Carolina State University at Raleigh",
  "north carolina state": "North Carolina State University at Raleigh",
  "suny bing": "Binghamton University",
  "suny binghamton": "Binghamton University",
  "suny buffalo": "University at Buffalo",
  "suny stony brook": "Stony Brook University",
  "vandy": "Vanderbilt University",
  "mcgill": "McGill University",
  "george mason": "George Mason University",
  "gmu": "George Mason University",
  "usc marshall": "University of Southern California",
  "usc viterbi": "University of Southern California",
  "cmu scs": "Carnegie Mellon University",
  "cmu ece": "Carnegie Mellon University",
  "cornell dyson": "Cornell University",
  "cornell eng": "Cornell University",
  "unc-chapel hill": "University of North Carolina at Chapel Hill",
  "ut dallas": "The University of Texas at Dallas",
  "utd": "The University of Texas at Dallas",
  "utk": "The University of Tennessee-Knoxville",
  "ut knoxville": "The University of Tennessee-Knoxville",
  "usna": "United States Naval Academy",
  "usma": "United States Military Academy",
  "west point": "United States Military Academy",
  "annapolis": "United States Naval Academy",
  "nyu abu dhabi": "New York University",
  "nyu shanghai": "New York University",
  "oregon state": "Oregon State University",
  "clemson": "Clemson University",
  "syracuse": "Syracuse University",
  "marquette": "Marquette University",
  "loyola marymount": "Loyola Marymount University",
  "lmu": "Loyola Marymount University",
  "scu": "Santa Clara University",
  "santa clara": "Santa Clara University",
  "gonzaga": "Gonzaga University",
  "creighton": "Creighton University",
  "depaul": "DePaul University",
  "howard": "Howard University",
  "spelman": "Spelman College",
  "morehouse": "Morehouse College",
  "cu boulder": "University of Colorado Boulder",
  "colorado boulder": "University of Colorado Boulder",
  "unh": "University of New Hampshire-Main Campus",
  "uri": "University of Rhode Island",
  "wvu": "West Virginia University",
  "upenn wharton": "University of Pennsylvania",
  "upenn seas": "University of Pennsylvania",
  "nyu stern": "New York University",
  "nyu tandon": "New York University",
  "nyu cas": "New York University",
  "cpp": "California State Polytechnic University-Pomona",
  "csuf": "California State University-Fullerton",
  "sjsu": "San Jose State University",
  "san jose state": "San Jose State University",
  "uw-madison": "University of Wisconsin-Madison",
  "uw-seattle": "University of Washington-Seattle Campus",
};

/**
 * Build a reverse map: full school name → list of abbreviations.
 * Useful for showing abbreviations in search results or enriching school data.
 */
export function getAbbreviationsForSchool(fullName: string): string[] {
  const abbreviations: string[] = [];
  for (const [abbreviation, name] of Object.entries(SCHOOL_ABBREVIATIONS)) {
    if (name === fullName) {
      abbreviations.push(abbreviation);
    }
  }
  return abbreviations;
}

/**
 * Look up a school's full name from an abbreviation query.
 * Returns all unique full names that match the query (exact or prefix match on abbreviation keys).
 */
export function resolveSchoolAbbreviation(query: string): string[] {
  const normalizedQuery = query.toLowerCase().trim();

  // First: exact abbreviation match
  const exactMatch = SCHOOL_ABBREVIATIONS[normalizedQuery];
  if (exactMatch) {
    return [exactMatch];
  }

  // Second: prefix match on abbreviation keys (e.g., "uc" matches "ucb", "ucla", "ucd", etc.)
  const prefixMatches = new Set<string>();
  for (const [abbreviation, fullName] of Object.entries(SCHOOL_ABBREVIATIONS)) {
    if (abbreviation.startsWith(normalizedQuery)) {
      prefixMatches.add(fullName);
    }
  }

  return Array.from(prefixMatches);
}
