export const COMMON_MAJORS: string[] = [
  "Accounting",
  "Actuarial Science",
  "Aerospace Engineering",
  "African American Studies",
  "Agricultural Science",
  "American Studies",
  "Anatomy",
  "Anthropology",
  "Applied Mathematics",
  "Architecture",
  "Art History",
  "Astronomy",
  "Biochemistry",
  "Bioengineering",
  "Biology",
  "Biomedical Engineering",
  "Biophysics",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Cognitive Science",
  "Communication Studies",
  "Comparative Literature",
  "Computational Biology",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Creative Writing",
  "Criminal Justice",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dentistry (Pre-Dental)",
  "Earth Science",
  "East Asian Studies",
  "Ecology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Entrepreneurship",
  "Environmental Engineering",
  "Environmental Science",
  "Ethnic Studies",
  "Exercise Science",
  "Fashion Design",
  "Film Studies",
  "Finance",
  "Food Science",
  "Foreign Languages",
  "Forensic Science",
  "French",
  "Gender Studies",
  "Genetics",
  "Geography",
  "Geology",
  "German",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Business",
  "International Relations",
  "Japanese",
  "Journalism",
  "Kinesiology",
  "Latin American Studies",
  "Law (Pre-Law)",
  "Linguistics",
  "Management",
  "Marine Biology",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Medicine (Pre-Med)",
  "Microbiology",
  "Middle Eastern Studies",
  "Military Science",
  "Molecular Biology",
  "Music",
  "Music Education",
  "Neuroscience",
  "Nuclear Engineering",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Oceanography",
  "Operations Management",
  "Optometry (Pre-Optometry)",
  "Pharmacy (Pre-Pharmacy)",
  "Philosophy",
  "Photography",
  "Physical Therapy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Real Estate",
  "Religious Studies",
  "Robotics",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Special Education",
  "Speech Pathology",
  "Sports Management",
  "Statistics",
  "Studio Art",
  "Supply Chain Management",
  "Theater",
  "Undecided",
  "Urban Planning",
  "Veterinary Science (Pre-Vet)",
  "Visual Arts",
  "Zoology",
];
